# .NET Core
# Build and run tests for .NET Core solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/zh-cn/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive

pool: 'Azure Self-Host Pipeline'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU;x64;ARM64;ARM32;x86'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'src/cpp/build.ps1'
    arguments: '-Msys2Root "I:/msys64" -Clean'
    workingDirectory: 'src/cpp'
    showWarnings: true
    pwsh: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: nuget.config 
    noCache: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'