# Mirror
# Mirror and publish the main branch to Github.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

trigger:
- main

pool: 'Azure Self-Host Pipeline'

steps:
- task: PowerShell@2
  inputs:
    filePath: '.azurepipelines\scripts\mirror.ps1'
    arguments: '-DesUri $(DESURI) -Branch $(BRANCH)'
    failOnStderr: true
    showWarnings: true
    pwsh: true
    runScriptInSeparateScope: true
  env:
    SRC_PAT: $(SRCPAT)
    DES_PAT: $(DESPAT)